services:
  - type: web
    name: dealhawk-api
    runtime: python
    rootDir: backend
    buildCommand: bash build.sh
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    plan: free
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: "false"
      - key: REDIS_URL
        value: ""
      - key: NAVER_CLIENT_ID
        value: swfhFspAnT0lTvZmRd7z
      - key: NAVER_CLIENT_SECRET
        value: OECscviOsx
      - key: FRONTEND_URL
        value: https://hotdeal-pi.vercel.app
      - key: PYTHON_VERSION
        value: "3.12.0"
